project_id = "svdbuvdrpoblcbdksxpj"

[functions.send-email-notification]
verify_jwt = false

[functions.check-overdue-tasks]
verify_jwt = false

[functions.send-project-report]
verify_jwt = false

[functions.process-scheduled-reports]
verify_jwt = false

[functions.invite-external-user]
verify_jwt = false

[functions.update-external-user-access]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-external-user-password]
verify_jwt = false

[functions.send-temporary-password]
verify_jwt = false